### ISSUE TITLE
No way to extract Err value.

### ISSUE THREAD

**Issue by Nashenas88** [oktal/result#3]
It seems the only way to retrieve the value within the `Err `is to call through to the storage struct. In Rust, this is done with a `match`, but there's nothing exactly like that in C++. Could you add an `unwrapErr` or add documentation on the proper way to extract values like you would with `match` in Rust?

**Comment by oktal** [comment]
Hello.

You are right, `unwrapErr` is currently missing. If you want to extract the error, you can use a combination of `then() / otherwise()` and use the `unwrapOr` on the final `Result`.

However, `unwrapErr` is still useful and I actually implemented in a private repo but forgot to update this repository. Would you like to contribute it ? It's actually pretty easy to add as it's the reverse of `unwrap()`

**Comment by Nashenas88** [comment]
Sure, I'll go ahead and add it. I think it's important that #1 also be resolved for this to happen.

**Comment by oktal** [comment]
Right, I just licensed it :)
