### ISSUE TITLE
Allow alternatives to `std::terminate`

### ISSUE THREAD

**Issue by Nashenas88** [oktal/result#7]
Currently several functions will call `std::terminate` on failure. It would be beneficial to allow users to customize this behavior, or possibly switch to using an exception (e.g., illegal state) so the user can catch it and then decide what to do next. While this would not be ideal, there may be circumstances where terminating is extremely inappropriate as there won't be a chance to do a proper cleanup.

**Comment by vorot93** [comment]
Functions calling `std::terminate` should be used with great care in any case (if ever) and panic on misuse is Rust's idiomatic behaviour (after which this library is modeled). Since Result monad potentially deprecates exceptions altogether (think about disabling them), there is no strong reason to pull those back in.
